export default {
  en: {
    title: "Privacy policy",
    sections: [
      { id: "controller", heading: "1. Controller and scope", paragraphs: [
        "AKIPASA MARKETING, S.L., in formation, provisional NIF B05706676, is identified as the controller for its own platform activities. Its contact and fiscal address is Avenida Diamante, 554, Urbanización Mijas La Nueva, 29650 Mijas, Málaga, Spain. Contact privacy@akipasa.com, or support@akipasa.com if necessary.",
        "This policy concerns visitors, account holders, creators, business representatives, people submitting or appearing in content, and people contacting the platform. Where AkiHQ processes a business customer's customer or staff records solely on that business's instructions, the business is the controller and the separate data-processing agreement applies. This policy does not replace that business's notice to its own customers and staff."
      ]},
      { id: "categories", heading: "2. Information processed and its sources", paragraphs: [
        "Information you provide can include registration and contact details, profile information and images, saved or followed places, achievement activity, contributions, reports, support correspondence, business-representation evidence and invoicing information. Optional fields must be distinguished from information necessary for the feature requested.",
        "Technical information can include IP address, browser and device details, authentication and security events, approximate area, request timestamps and the interactions described in the Cookie policy where enabled. Payments can produce customer, order, invoice, subscription and payment-status identifiers. Full card details are submitted to the payment provider rather than intended for storage in ordinary AkiPasa account records.",
        "Information can also come from the sign-in provider you choose, businesses or creators submitting information, payment providers, publicly available business directories, licensed or open datasets and publicly accessible business websites. A business listing may contain personal data, for example a sole trader's name or contact details. Public availability does not remove data-protection rights. Contact us to identify the source of a particular personal-data entry, request a correction or object to its use."
      ]},
      { id: "purposes", heading: "3. Purposes and legal bases", paragraphs: [
        "Account operation, saved items, requested community functions, subscriptions, achievement records and responses necessary to provide an individual user's service: performance of the contract or requested pre-contractual measures under GDPR Article 6(1)(b). This basis covers only objectively necessary processing, not all useful analytics or advertising.",
        "Communications with a company's representatives and verification of their authority: legitimate interests under Article 6(1)(f) in managing a genuine business relationship and preventing impersonation, subject to an interests assessment and the representative's rights. Where the individual is personally contracting, Article 6(1)(b) may instead apply to necessary processing.",
        "Service security, proportionate abuse prevention, investigating reports, maintaining appropriate evidence and defending legal claims: legitimate interests under Article 6(1)(f), or Article 6(1)(c) where a specific legal duty applies. Interests are balanced against the individual's rights, especially those of minors.",
        "Invoicing, tax and accounting duties, valid authority requests, legally required moderation measures and handling statutory rights: legal obligations under Article 6(1)(c), including applicable Spanish tax, commercial, consumer, digital-service and data-protection law.",
        "Optional behavioural personalisation, non-essential analytics, advertising tracking and optional marketing: consent under Article 6(1)(a), together with the applicable electronic-communications rules. A strictly applicable existing-customer marketing exception must be separately assessed; it is not inferred from registering, a public email address or accepting the terms.",
        "Publishing relevant public professional contact information in discovery listings: a documented legitimate-interest assessment under Article 6(1)(f), limited to appropriate professional information. This does not authorise bulk publication of private contact details or disregard of Article 14 information duties."
      ]},
      { id: "location", heading: "4. Location, maps and motion effects", paragraphs: [
        "Device location is requested when you choose a location-dependent function. You can instead select an area manually where that option is offered. Browser or operating-system permission is separate from agreeing to cookies. The applicable information must explain whether a particular feature processes coordinates only on the device or sends them to a server, and whether it records a visit or check-in. This package does not make an unverified claim that precise coordinates are never transmitted or stored.",
        "Optional device-orientation or motion access can animate holographic passport artwork. It is not required for ordinary browsing and does not itself authorise location tracking or marketing. Where a browser requires an additional permission, accepting cookies does not bypass that permission. The actual sensor transmission and storage behaviour must be verified before the final notice promises on-device-only processing.",
        "Map, image and external-media requests can disclose technical connection information to their providers. The deployed provider inventory and any non-essential tracking must be covered by the Cookie policy and relevant choices."
      ]},
      { id: "public", heading: "5. Public information and business access", paragraphs: [
        "Information deliberately published in a profile, community contribution or business listing may be visible to other users and search engines. Review the relevant visibility controls before publishing. Removing a page from AkiPasa does not immediately remove independent search-engine caches; applicable removal requests can still be made.",
        "A venue does not automatically receive a visitor's email address, identity or precise location merely because its listing was viewed. Where a feature intentionally sends a message, booking enquiry or other identifiable data to a business, that transfer and the business's role must be explained at the point of use. Business statistics should be aggregated appropriately; pseudonymous identifiers are not automatically anonymous."
      ]},
      { id: "recipients", heading: "6. Recipients and providers", paragraphs: [
        "Access may be given, where necessary, to authorised staff; hosting, content-delivery, authentication, database, email, mapping, analytics and support providers; payment providers; professional advisers; and authorities with a lawful entitlement. Public content is available to its intended audience. A transfer in a corporate reorganisation must have an appropriate basis, safeguards and notice; it is not an unlimited permission to sell personal information.",
        "The architecture identified for review includes Cloudflare, Supabase, Resend, Google sign-in and Google analytics/reporting services, and Stripe for payments. Their exact contracting entities, active products, roles, locations, retention and contractual safeguards require reconciliation with the deployed configuration. Some payment and sign-in processing is undertaken by the provider as an independent controller, rather than solely on AkiPasa's instructions.",
        "AI-assisted support and moderation are identified in the repository. The provider, data fields transmitted, retention and training settings must be established before external AI processing is covered by a final notice. A general reference to service providers must not be used to conceal a materially different processing purpose."
      ]},
      { id: "transfers", heading: "7. International transfers", paragraphs: [
        "An EU database region does not, by itself, guarantee that every support, backup, telemetry or subprocessor operation remains in the EEA. Each relevant provider and destination must be assessed.",
        "Where personal data are transferred outside the EEA, the applicable mechanism must be identified: an applicable European Commission adequacy decision, or appropriate safeguards such as the applicable standard contractual clauses together with any necessary supplementary measures and transfer assessment. Reliance on an adequacy framework must be verified for the actual recipient and covered service. Contact privacy@akipasa.com for information or a copy of the relevant safeguards, with lawful confidential information redacted. No provider-specific transfer mechanism is certified by this draft."
      ]},
      { id: "retention", heading: "8. Retention and deletion criteria", paragraphs: [
        "Account and service records are retained for the active relationship to the extent needed for the requested service; following closure, data are deleted or anonymised except for specifically justified restricted records. Public contributions are handled in light of the deletion request, other people's rights and any legal requirement, not under a blanket perpetual licence.",
        "Billing and commercial accounting records may require six years' retention under Spanish commercial law. Tax records are retained for the applicable tax period, generally four years but subject to interruption and special rules. These periods do not justify keeping every profile field, location or behavioural event for six years.",
        "Support and moderation records are retained for handling the matter and the applicable, specifically assessed challenge or claim period. Security logs are retained only for a proportionate documented security period. Optional behavioural data must have a defined maximum life and be deleted or anonymised when no longer necessary; a browser queue bounded by event count is not a complete server-retention policy.",
        "Deletion may require restricted preservation under Spanish data-blocking rules or a specific legal hold. Backups must expire under a documented schedule and must not be routinely restored into active use after deletion. The operational schedule, inactivity review, exact maxima and deletion tests remain release requirements for this draft; it does not promise unverified 30-, 90- or 180-day technical erasure."
      ]},
      { id: "automated", heading: "9. Personalisation, profiling and AI", paragraphs: [
        "Optional recommendation personalisation can use interactions to infer interests in places or categories. Refusing this processing must leave a usable non-personalised service where the feature is not necessary for the requested contract. We do not authorise inference of sensitive characteristics from venue choices under these terms.",
        "Automated systems may assist with filtering, detecting possible abuse, prioritising reports and drafting support responses. Their use, important limitations and any restrictions must be explained under the content policy. A person can challenge a relevant outcome and request human review. This draft does not claim that every automated restriction has already been audited or that all processing falls outside GDPR Article 22. A decision with legal or similarly significant effects requires a specific lawful basis and safeguards; ordinary optional recommendation consent is not blanket authority for it."
      ]},
      { id: "rights", heading: "10. Your rights and complaints", paragraphs: [
        "Subject to their legal conditions, you may request access, correction, erasure, restriction and portability of your personal data; object to processing based on legitimate interests; withdraw consent at any time without affecting prior lawful processing; and exercise applicable rights concerning automated decisions. Objection to direct marketing stops that marketing. Account export and deletion controls, where available, supplement rather than replace the email and postal routes.",
        "Requests are generally free and must be answered within one month. A necessary extension of up to two further months must be explained within the first month. Additional identity evidence may be sought only where proportionate to reasonable doubts; a full identity-document copy is not automatically required.",
        "You may lodge a complaint with the Spanish Data Protection Agency (AEPD), through www.aepd.es, or another competent supervisory authority, and seek a judicial remedy. AkiPasa's approval is not required before making a regulatory complaint. Contacting us first may help resolve the matter but does not remove your statutory remedies."
      ]},
      { id: "updates", heading: "11. Information duties and changes", paragraphs: [
        "Where data were obtained indirectly, information must be provided within the applicable GDPR Article 14 deadline, generally within one month or earlier at the first communication or disclosure where required. A publicly accessible policy does not automatically satisfy that duty for every imported personal-data record. Any exemption requires an actual legal assessment and appropriate safeguards.",
        "Material changes will be explained before new processing where required. New consent is sought where the change requires it; silently editing this policy is not consent. The company must assess whether a DPO, impact assessment or additional protections for minors are required in light of actual processing."
      ]}
    ]
  },
  es: {
    title: "Política de privacidad",
    sections: [
      { id: "controller", heading: "1. Responsable y ámbito", paragraphs: [
        "AKIPASA MARKETING, S.L., en formación, con NIF provisional B05706676, se identifica como responsable de sus propias actividades de plataforma. Su dirección de contacto y domicilio fiscal es Avenida Diamante, 554, Urbanización Mijas La Nueva, 29650 Mijas, Málaga, España. Puede contactar mediante privacy@akipasa.com o, cuando sea necesario, support@akipasa.com.",
        "Esta política comprende visitantes, titulares de cuentas, creadores, representantes de negocios, personas que aportan contenidos o aparecen en ellos y personas que contactan con la plataforma. Cuando AkiHQ trate datos de clientes o personal de un negocio exclusivamente siguiendo las instrucciones de este, el negocio será responsable y se aplicará el acuerdo de encargo de tratamiento. Esta política no sustituye la información que ese negocio debe facilitar a sus propios clientes y trabajadores."
      ]},
      { id: "categories", heading: "2. Información tratada y procedencia", paragraphs: [
        "La información que facilita puede incluir datos de registro y contacto, perfil e imágenes, lugares guardados o seguidos, actividad de logros, aportaciones, denuncias, comunicaciones de soporte, pruebas de representación empresarial y datos de facturación. Los campos opcionales deberán distinguirse de los datos necesarios para la función solicitada.",
        "La información técnica puede comprender dirección IP, navegador y dispositivo, eventos de autenticación y seguridad, zona aproximada, fechas de solicitudes e interacciones descritas en la Política de cookies cuando estén habilitadas. Los pagos pueden generar identificadores de cliente, pedido, factura, suscripción y estado del pago. Los datos completos de tarjeta se facilitan al proveedor de pagos y no están destinados a almacenarse en los registros ordinarios de cuenta de AkiPasa.",
        "También puede recibirse información del proveedor de acceso elegido, de negocios o creadores que aporten información, de proveedores de pago, directorios empresariales públicos, conjuntos de datos licenciados o abiertos y sitios empresariales accesibles públicamente. Una ficha puede contener datos personales, por ejemplo el nombre o contacto de un autónomo. Su disponibilidad pública no elimina los derechos de protección de datos. Puede solicitar la procedencia de una entrada concreta, su corrección u oponerse a su utilización."
      ]},
      { id: "purposes", heading: "3. Finalidades y bases jurídicas", paragraphs: [
        "Funcionamiento de la cuenta, elementos guardados, funciones de comunidad solicitadas, suscripciones, registros de logros y respuestas necesarias para prestar el servicio individual: ejecución del contrato o medidas precontractuales solicitadas conforme al artículo 6.1.b del RGPD. Esta base comprende únicamente tratamientos objetivamente necesarios, no cualquier analítica o publicidad útil.",
        "Comunicaciones con representantes de sociedades y verificación de su representación: interés legítimo del artículo 6.1.f en gestionar relaciones empresariales reales y prevenir suplantaciones, sujeto a ponderación y a los derechos de la persona. Cuando esta contrate personalmente, podrá aplicarse en su lugar el artículo 6.1.b a los tratamientos necesarios.",
        "Seguridad del servicio, prevención proporcionada de abusos, investigación de denuncias, conservación adecuada de pruebas y defensa de reclamaciones: interés legítimo del artículo 6.1.f, o artículo 6.1.c cuando exista una obligación legal concreta. Se ponderan los derechos de las personas afectadas, especialmente de los menores.",
        "Facturación, obligaciones tributarias y contables, requerimientos válidos de autoridades, medidas de moderación legalmente exigibles y tramitación de derechos: obligaciones legales del artículo 6.1.c, incluidas las normas españolas tributarias, mercantiles, de consumo, servicios digitales y protección de datos aplicables.",
        "Personalización conductual opcional, analítica no necesaria, seguimiento publicitario y comunicaciones comerciales opcionales: consentimiento del artículo 6.1.a, junto con las normas aplicables sobre comunicaciones electrónicas. Cualquier excepción estrictamente aplicable para clientes previos deberá evaluarse por separado; no se presume por registrarse, publicar un correo o aceptar las condiciones.",
        "Publicación de información profesional de contacto pertinente en fichas: ponderación documentada de interés legítimo conforme al artículo 6.1.f, limitada a información profesional adecuada. No autoriza la publicación masiva de contactos privados ni el incumplimiento del deber informativo del artículo 14."
      ]},
      { id: "location", heading: "4. Ubicación, mapas y efectos de movimiento", paragraphs: [
        "La ubicación del dispositivo se solicita cuando elige una función que depende de ella. Podrá seleccionar una zona manualmente cuando se ofrezca esa alternativa. El permiso del navegador o sistema operativo es independiente de la aceptación de cookies. La información correspondiente deberá explicar si una función concreta trata coordenadas únicamente en el dispositivo o las envía a un servidor y si registra una visita o registro de presencia. Este paquete no afirma sin verificación que las coordenadas precisas nunca se transmitan o almacenen.",
        "El acceso opcional a orientación o movimiento puede animar las imágenes holográficas del pasaporte. No es necesario para la navegación ordinaria ni autoriza por sí solo seguimiento de ubicación o publicidad. Cuando el navegador exija un permiso adicional, aceptar cookies no permite eludirlo. Antes de prometer un tratamiento exclusivamente local en el aviso definitivo deberá verificarse la transmisión y conservación efectivas de datos de sensores.",
        "Las solicitudes de mapas, imágenes y contenidos externos pueden comunicar información técnica de conexión a sus proveedores. La Política de cookies y los controles correspondientes deberán cubrir el inventario de proveedores desplegados y cualquier seguimiento no necesario."
      ]},
      { id: "public", heading: "5. Información pública y acceso de negocios", paragraphs: [
        "La información publicada deliberadamente en un perfil, aportación comunitaria o ficha empresarial puede ser visible para otros usuarios y buscadores. Revise los controles de visibilidad antes de publicar. Retirar una página de AkiPasa no elimina inmediatamente las copias independientes de buscadores; siguen siendo posibles las solicitudes de retirada que procedan.",
        "Un local no recibe automáticamente el correo, identidad o ubicación precisa de una persona por una mera visita a su ficha. Cuando una función envíe deliberadamente un mensaje, consulta de reserva u otros datos identificativos a un negocio, deberá explicarse la comunicación y el papel del negocio en ese momento. Las estadísticas empresariales deberán agregarse adecuadamente; un identificador seudónimo no es automáticamente anónimo."
      ]},
      { id: "recipients", heading: "6. Destinatarios y proveedores", paragraphs: [
        "Cuando sea necesario, podrán acceder empleados autorizados; proveedores de alojamiento, distribución de contenidos, autenticación, bases de datos, correo, mapas, analítica y soporte; proveedores de pagos; asesores profesionales; y autoridades legalmente legitimadas. Los contenidos públicos son accesibles a su público previsto. Una transmisión en una reorganización empresarial exige base adecuada, garantías e información; no constituye permiso ilimitado para vender datos personales.",
        "La arquitectura identificada para revisión incluye Cloudflare, Supabase, Resend, acceso mediante Google y servicios de analítica e informes de Google, así como Stripe para pagos. Sus entidades contratantes, productos activos, funciones, ubicaciones, conservación y garantías contractuales deben conciliarse con el despliegue real. Parte del tratamiento de pagos y acceso federado corresponde al proveedor como responsable independiente y no exclusivamente por instrucciones de AkiPasa.",
        "El repositorio identifica soporte y moderación asistidos por IA. Antes de cubrir el tratamiento externo por IA en un aviso definitivo deben determinarse proveedor, campos enviados, conservación y ajustes de entrenamiento. Una referencia genérica a proveedores no permite ocultar una finalidad de tratamiento materialmente distinta."
      ]},
      { id: "transfers", heading: "7. Transferencias internacionales", paragraphs: [
        "La ubicación europea de una base de datos no garantiza por sí sola que soporte, copias de seguridad, telemetría o subencargados operen exclusivamente dentro del EEE. Deben evaluarse cada proveedor y destino pertinentes.",
        "Cuando se transfieran datos fuera del EEE, deberá identificarse el mecanismo aplicable: una decisión de adecuación pertinente de la Comisión Europea o garantías adecuadas, como las cláusulas contractuales tipo aplicables, junto con las medidas complementarias y evaluación necesarias. La aplicación de un marco de adecuación debe comprobarse para el destinatario y servicio efectivos. Puede solicitar información o copia de las garantías a privacy@akipasa.com, con supresión de información confidencial legalmente protegida. Este borrador no certifica ningún mecanismo de transferencia concreto de un proveedor."
      ]},
      { id: "retention", heading: "8. Criterios de conservación y supresión", paragraphs: [
        "Los datos de cuenta y servicio se conservan durante la relación activa en la medida necesaria para la prestación solicitada; tras la baja se suprimen o anonimizan, salvo registros concretos cuya conservación restringida esté justificada. Las aportaciones públicas se gestionan considerando la solicitud de supresión, los derechos ajenos y las obligaciones legales, no mediante una licencia perpetua indiscriminada.",
        "Los documentos de facturación y contabilidad mercantil pueden exigir seis años de conservación conforme al Derecho mercantil español. Los datos tributarios se conservan durante el plazo aplicable, generalmente cuatro años, sujeto a interrupciones y reglas especiales. Estos plazos no justifican conservar todos los campos de perfil, ubicaciones o eventos conductuales durante seis años.",
        "Los registros de soporte y moderación se conservan para tramitar el asunto y durante el plazo de impugnación o reclamación concretamente evaluado. Los registros de seguridad se conservan únicamente durante un plazo documentado y proporcionado. Los datos conductuales opcionales deben tener una duración máxima y suprimirse o anonimizarse cuando dejen de ser necesarios; limitar una cola del navegador por número de eventos no constituye una política completa de conservación en servidores.",
        "La supresión puede requerir bloqueo conforme a la normativa española o una conservación legal específica. Las copias de seguridad deberán caducar conforme a un calendario documentado y no reintroducirse ordinariamente en uso activo tras una supresión. El calendario operativo, revisión de inactividad, máximos concretos y pruebas de borrado siguen siendo requisitos de publicación definitiva; este borrador no promete plazos técnicos de borrado de 30, 90 o 180 días no verificados."
      ]},
      { id: "automated", heading: "9. Personalización, perfiles e IA", paragraphs: [
        "La personalización opcional de recomendaciones puede utilizar interacciones para inferir intereses en lugares o categorías. Rechazarla debe permitir un servicio no personalizado utilizable cuando no sea necesaria para el contrato solicitado. Estas condiciones no autorizan inferir características sensibles a partir de los locales elegidos.",
        "Los sistemas automatizados pueden asistir en filtrado, detección de posibles abusos, priorización de avisos y redacción de respuestas de soporte. Su utilización, limitaciones relevantes y restricciones deberán explicarse conforme a la política de contenidos. La persona afectada puede cuestionar un resultado relevante y solicitar revisión humana. Este borrador no afirma que todas las restricciones automatizadas estén auditadas ni que todos los tratamientos queden fuera del artículo 22 del RGPD. Una decisión con efectos jurídicos o similares significativos requiere base específica y garantías; el consentimiento ordinario a recomendaciones no constituye autorización general para ella."
      ]},
      { id: "rights", heading: "10. Derechos y reclamaciones", paragraphs: [
        "Cuando concurran sus requisitos legales, puede solicitar acceso, rectificación, supresión, limitación y portabilidad; oponerse a tratamientos basados en interés legítimo; retirar el consentimiento en cualquier momento sin afectar al tratamiento lícito anterior; y ejercer los derechos aplicables a decisiones automatizadas. La oposición a publicidad directa pone fin a esa publicidad. Los controles de exportación y supresión de cuenta, cuando existan, complementan y no sustituyen las vías de correo electrónico y postal.",
        "Las solicitudes son, en general, gratuitas y deben responderse en un mes. Si resulta necesaria una ampliación de hasta dos meses adicionales, deberá explicarse dentro del primer mes. Solo podrá pedirse prueba adicional de identidad proporcionada ante dudas razonables; no se exige automáticamente una copia íntegra del documento de identidad.",
        "Puede presentar una reclamación ante la Agencia Española de Protección de Datos (AEPD), mediante www.aepd.es, u otra autoridad de control competente, y acudir a los tribunales. No necesita autorización de AkiPasa para reclamar ante una autoridad. Contactar previamente puede facilitar una solución, sin eliminar sus derechos legales."
      ]},
      { id: "updates", heading: "11. Deberes informativos y cambios", paragraphs: [
        "Cuando los datos se obtengan indirectamente, la información debe facilitarse en el plazo aplicable del artículo 14 del RGPD, generalmente dentro de un mes o antes al realizar la primera comunicación o divulgación cuando corresponda. Publicar una política no satisface automáticamente ese deber para cada registro personal importado. Cualquier excepción exige una evaluación jurídica real y garantías adecuadas.",
        "Los cambios relevantes se explicarán antes de nuevos tratamientos cuando sea exigible. Se solicitará nuevo consentimiento cuando el cambio lo requiera; editar silenciosamente esta política no constituye consentimiento. La sociedad debe evaluar si son necesarios un delegado de protección de datos, una evaluación de impacto o garantías adicionales para menores conforme a los tratamientos efectivos."
      ]}
    ]
  }
} as const;
