// Generated by scripts/generate-command-registry.mjs. Do not edit.
import command0 from "./expenses";
import command1 from "./investor";
import command2 from "./revenue";
import command3 from "./status";
import command4 from "./telegram-test";

import type { AutomationCommand } from "./types";

export const generatedCommands: AutomationCommand[] = [
  command0,
  command1,
  command2,
  command3,
  command4,
];
