export type SpainLocation = {
  es: string;
  en: string;
  province: string;
  latitude: number;
  longitude: number;
};

// Province capitals, autonomous cities and useful Costa areas provide a
// credential-free nationwide search centre. Venues retain exact coordinates,
// so businesses can list in every Spanish municipality.
export const spainLocations = {
  "a-coruna": {
    es: "A Coruña",
    en: "A Coruña",
    province: "A Coruña",
    latitude: 43.3623,
    longitude: -8.4115,
  },
  albacete: {
    es: "Albacete",
    en: "Albacete",
    province: "Albacete",
    latitude: 38.9943,
    longitude: -1.8585,
  },
  alicante: {
    es: "Alicante",
    en: "Alicante",
    province: "Alicante",
    latitude: 38.3452,
    longitude: -0.481,
  },
  almeria: {
    es: "Almería",
    en: "Almería",
    province: "Almería",
    latitude: 36.834,
    longitude: -2.4637,
  },
  avila: {
    es: "Ávila",
    en: "Ávila",
    province: "Ávila",
    latitude: 40.6565,
    longitude: -4.6818,
  },
  badajoz: {
    es: "Badajoz",
    en: "Badajoz",
    province: "Badajoz",
    latitude: 38.8794,
    longitude: -6.9707,
  },
  barcelona: {
    es: "Barcelona",
    en: "Barcelona",
    province: "Barcelona",
    latitude: 41.3874,
    longitude: 2.1686,
  },
  bilbao: {
    es: "Bilbao",
    en: "Bilbao",
    province: "Bizkaia",
    latitude: 43.263,
    longitude: -2.935,
  },
  burgos: {
    es: "Burgos",
    en: "Burgos",
    province: "Burgos",
    latitude: 42.3439,
    longitude: -3.6969,
  },
  caceres: {
    es: "Cáceres",
    en: "Cáceres",
    province: "Cáceres",
    latitude: 39.4753,
    longitude: -6.3724,
  },
  cadiz: {
    es: "Cádiz",
    en: "Cádiz",
    province: "Cádiz",
    latitude: 36.5271,
    longitude: -6.2886,
  },
  castellon: {
    es: "Castelló de la Plana",
    en: "Castellón",
    province: "Castellón",
    latitude: 39.9864,
    longitude: -0.0513,
  },
  ceuta: {
    es: "Ceuta",
    en: "Ceuta",
    province: "Ceuta",
    latitude: 35.8894,
    longitude: -5.3213,
  },
  "ciudad-real": {
    es: "Ciudad Real",
    en: "Ciudad Real",
    province: "Ciudad Real",
    latitude: 38.9848,
    longitude: -3.9274,
  },
  cordoba: {
    es: "Córdoba",
    en: "Córdoba",
    province: "Córdoba",
    latitude: 37.8882,
    longitude: -4.7794,
  },
  cuenca: {
    es: "Cuenca",
    en: "Cuenca",
    province: "Cuenca",
    latitude: 40.0704,
    longitude: -2.1374,
  },
  "donostia-san-sebastian": {
    es: "Donostia / San Sebastián",
    en: "San Sebastián",
    province: "Gipuzkoa",
    latitude: 43.3183,
    longitude: -1.9812,
  },
  girona: {
    es: "Girona",
    en: "Girona",
    province: "Girona",
    latitude: 41.9794,
    longitude: 2.8214,
  },
  granada: {
    es: "Granada",
    en: "Granada",
    province: "Granada",
    latitude: 37.1773,
    longitude: -3.5986,
  },
  guadalajara: {
    es: "Guadalajara",
    en: "Guadalajara",
    province: "Guadalajara",
    latitude: 40.6333,
    longitude: -3.1669,
  },
  huelva: {
    es: "Huelva",
    en: "Huelva",
    province: "Huelva",
    latitude: 37.2614,
    longitude: -6.9447,
  },
  huesca: {
    es: "Huesca",
    en: "Huesca",
    province: "Huesca",
    latitude: 42.1401,
    longitude: -0.4089,
  },
  jaen: {
    es: "Jaén",
    en: "Jaén",
    province: "Jaén",
    latitude: 37.7796,
    longitude: -3.7849,
  },
  "las-palmas": {
    es: "Las Palmas de Gran Canaria",
    en: "Las Palmas",
    province: "Las Palmas",
    latitude: 28.1235,
    longitude: -15.4363,
  },
  leon: {
    es: "León",
    en: "León",
    province: "León",
    latitude: 42.5987,
    longitude: -5.5671,
  },
  lleida: {
    es: "Lleida",
    en: "Lleida",
    province: "Lleida",
    latitude: 41.6176,
    longitude: 0.62,
  },
  logrono: {
    es: "Logroño",
    en: "Logroño",
    province: "La Rioja",
    latitude: 42.4627,
    longitude: -2.4449,
  },
  lugo: {
    es: "Lugo",
    en: "Lugo",
    province: "Lugo",
    latitude: 43.0123,
    longitude: -7.5559,
  },
  madrid: {
    es: "Madrid",
    en: "Madrid",
    province: "Madrid",
    latitude: 40.4168,
    longitude: -3.7038,
  },
  malaga: {
    es: "Málaga",
    en: "Málaga",
    province: "Málaga",
    latitude: 36.7213,
    longitude: -4.4214,
  },
  melilla: {
    es: "Melilla",
    en: "Melilla",
    province: "Melilla",
    latitude: 35.2923,
    longitude: -2.9381,
  },
  murcia: {
    es: "Murcia",
    en: "Murcia",
    province: "Murcia",
    latitude: 37.9922,
    longitude: -1.1307,
  },
  ourense: {
    es: "Ourense",
    en: "Ourense",
    province: "Ourense",
    latitude: 42.3358,
    longitude: -7.8639,
  },
  oviedo: {
    es: "Oviedo",
    en: "Oviedo",
    province: "Asturias",
    latitude: 43.3619,
    longitude: -5.8494,
  },
  palencia: {
    es: "Palencia",
    en: "Palencia",
    province: "Palencia",
    latitude: 42.0096,
    longitude: -4.5288,
  },
  palma: {
    es: "Palma",
    en: "Palma",
    province: "Illes Balears",
    latitude: 39.5696,
    longitude: 2.6502,
  },
  pamplona: {
    es: "Pamplona / Iruña",
    en: "Pamplona",
    province: "Navarra",
    latitude: 42.8125,
    longitude: -1.6458,
  },
  pontevedra: {
    es: "Pontevedra",
    en: "Pontevedra",
    province: "Pontevedra",
    latitude: 42.4299,
    longitude: -8.6446,
  },
  salamanca: {
    es: "Salamanca",
    en: "Salamanca",
    province: "Salamanca",
    latitude: 40.9701,
    longitude: -5.6635,
  },
  "santa-cruz-tenerife": {
    es: "Santa Cruz de Tenerife",
    en: "Santa Cruz de Tenerife",
    province: "Santa Cruz de Tenerife",
    latitude: 28.4636,
    longitude: -16.2518,
  },
  santander: {
    es: "Santander",
    en: "Santander",
    province: "Cantabria",
    latitude: 43.4623,
    longitude: -3.81,
  },
  segovia: {
    es: "Segovia",
    en: "Segovia",
    province: "Segovia",
    latitude: 40.9429,
    longitude: -4.1088,
  },
  sevilla: {
    es: "Sevilla",
    en: "Seville",
    province: "Sevilla",
    latitude: 37.3891,
    longitude: -5.9845,
  },
  soria: {
    es: "Soria",
    en: "Soria",
    province: "Soria",
    latitude: 41.7666,
    longitude: -2.479,
  },
  tarragona: {
    es: "Tarragona",
    en: "Tarragona",
    province: "Tarragona",
    latitude: 41.1189,
    longitude: 1.2445,
  },
  teruel: {
    es: "Teruel",
    en: "Teruel",
    province: "Teruel",
    latitude: 40.3456,
    longitude: -1.1065,
  },
  toledo: {
    es: "Toledo",
    en: "Toledo",
    province: "Toledo",
    latitude: 39.8628,
    longitude: -4.0273,
  },
  valencia: {
    es: "València",
    en: "Valencia",
    province: "Valencia",
    latitude: 39.4699,
    longitude: -0.3763,
  },
  valladolid: {
    es: "Valladolid",
    en: "Valladolid",
    province: "Valladolid",
    latitude: 41.6523,
    longitude: -4.7245,
  },
  "vitoria-gasteiz": {
    es: "Vitoria-Gasteiz",
    en: "Vitoria-Gasteiz",
    province: "Álava",
    latitude: 42.8467,
    longitude: -2.6716,
  },
  zamora: {
    es: "Zamora",
    en: "Zamora",
    province: "Zamora",
    latitude: 41.5035,
    longitude: -5.7446,
  },
  zaragoza: {
    es: "Zaragoza",
    en: "Zaragoza",
    province: "Zaragoza",
    latitude: 41.6488,
    longitude: -0.8891,
  },
  fuengirola: {
    es: "Fuengirola",
    en: "Fuengirola",
    province: "Málaga",
    latitude: 36.539,
    longitude: -4.624,
  },
  boliches: {
    es: "Los Boliches",
    en: "Los Boliches",
    province: "Málaga",
    latitude: 36.551,
    longitude: -4.615,
  },
  carvajal: {
    es: "Torreblanca / Carvajal",
    en: "Torreblanca / Carvajal",
    province: "Málaga",
    latitude: 36.569,
    longitude: -4.595,
  },
  mijas: {
    es: "Mijas",
    en: "Mijas",
    province: "Málaga",
    latitude: 36.596,
    longitude: -4.637,
  },
} as const satisfies Record<string, SpainLocation>;

export type SpainLocationKey = keyof typeof spainLocations;
export function isSpainLocation(value: string): value is SpainLocationKey {
  return Object.prototype.hasOwnProperty.call(spainLocations, value);
}
export const sortedSpainLocations = Object.entries(spainLocations).sort(
  (a, b) => a[1].es.localeCompare(b[1].es, "es"),
);
